# Version
version: '{build}'

# Branches
#branches:
#  only: master

skip_tags: true

# Build Server Image
image: Visual Studio 2017

# Install Script
install:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: $env:APPVEYOR_BUILD_NUMBER_PADDED = ([int]$env:appveyor_build_number).ToString("00000")

# Build Script
build_script:
  - ps: . .\build.ps1

# Tests
test: false

# Define artifacts
artifacts:
  - path: 'build\*.nupkg'

# Deploy
deploy: 
  - provider: NuGet
    server: https://ci.appveyor.com/nuget/aliumfx
    api_key:
      secure: 9UKX4yVinYkkf7GHubwvhXMSI3f4aqpbvETU6KbF9RQ=
    skip_symbols: true
    
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: release
      appveyor_repo_tag: true

# Notifications
notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: framework
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true