# Version
version: '{build}'

# Branches
#branches:
#  only: master

skip_tags: true

# Build Server Image
image: Visual Studio 2017

# Install Script
install:
  - cmd: git submodule init
  - cmd: git submodule update
  - ps: $env:APPVEYOR_BUILD_NUMBER_PADDED = ([int]$env:appveyor_build_number).ToString("00000")

# Build Script
build_script:
  - ps: . .\build.ps1

# Tests
test:
  assemblies:
    - 'test\**\*.Tests.dll'
  
  categories:
    except:
      - CIIgnore

# Define artifacts
artifacts:
  - path: 'build\*.nupkg'

# Deploy
deploy: 
  - provider: NuGet
    server: https://www.myget.org/F/aliumfx/api/v2/package
    symbol_server: https://www.myget.org/F/aliumfx/symbols/api/v2/package
    api_key:
      secure: 8BRAlgURo0mIptDMIPCGEaxift9MAA3R0CisisiR6aIFZDk2Ol/2cyyQFPCWJeCg
    
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      branch: release
      appveyor_repo_tag: true

# Notifications
notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: framework
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true