# Version
version: 0.1.0-{branch}-ci-{build}

# Branches
#branches:
#  only: master

skip_tags: true

# Build Server Image
image: Visual Studio 2017

# Install Script
install:
  - cmd: git submodule init
  - cmd: git submodule update

# Build Script
build_script:
  - ps: . .\build.ps1

# Tests
test: false

# Deploy
deploy: false

# Notifications
notifications:
  - provider: Slack
    incoming_webhook: https://hooks.slack.com/services/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
    channel: framework
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true