trigger:
  branches:
    include:
    - master
    - features/*
  paths:
    exclude:
    - .editorconfig
    - LICENSE
    - README.md
    - appveyor.yml
    - .travis.yml
    - .circleci/config.yml
    
pool:
  vmImage: 'vs2017-win2016'

variables:
  buildConfiguration: 'Release'
  
steps:
- task: PowerShell@2
  inputs:
    filePath: '.\install.ps1'
    pwsh: true
  displayName: Install .NET Core

- task: PowerShell@2
  inputs:
    filePath: '.\install.ps1'
    pwsh: true
  displayName: Install .NET Core

- task: PublishTestResults@2
  inputs:
    testRunner: VSTest
    testResultsFiles: 'build/testResults/**/*.xml'

