trigger:
  branches:
    include:
      - develop
      - master
      - feature/*
      - bugfix/*
      - hotfix/*
  paths:
    exclude:
      - .editorconfig
      - LICENSE
      - README.md
      - appveyor.yml
      - .travis.yml
      - .circleci/config.yml

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

variables:
  buildConfiguration: 'Release'

steps:
  - script: git submodule init
  - script: git submodule update

  - task: PowerShell@2
    inputs:
      filePath: 'install.ps1'
      pwsh: true
    displayName: Install .NET Core

  - task: PowerShell@2
    inputs:
      filePath: 'build.ps1'
      pwsh: true
    displayName: Build Alium Framework

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: 'build/test-results/**/*.xml'
